services:
  redis:
    container_name: redis
    image: redis:7.2
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - type: volume
        source: redis-data
        target: /data
      - type: bind
        source: services/redis/dev/redis.conf
        target: /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
