# 외부 접속 허용
bind 0.0.0.0
port 6379
tcp-backlog 511

# Docker에서는 반드시 'no'
daemonize no
supervised no
pidfile /var/run/redis.pid

loglevel notice
logfile ""

maxmemory 256mb
maxmemory-policy allkeys-lru

# 900초(15분)마다 1개 이상의 키 변경 시 RDB 저장
save 900 1
save 300 10
save 60 10000

rdbcompression yes
dir /data
dbfilename dump.rdb

requirepass 1234
protected-mode yes

# replicaof <masterip> <masterport>
# masterauth <password>

appendonly no
appendfilename "appendonly.aof"
appendfsync everysec

latency-monitor-threshold 0

tcp-keepalive 300
