-- rollback for 2026-03-31_bind_uuid_columns_char36.sql

ALTER TABLE auth_accounts
	MODIFY COLUMN id BINARY(16) NOT NULL,
	MODIFY COLUMN user_id BINARY(16) NOT NULL;

ALTER TABLE auth_login_attempts
	MODIFY COLUMN id BINARY(16) NOT NULL;

ALTER TABLE mfa_factors
	MODIFY COLUMN id BINARY(16) NOT NULL,
	MODIFY COLUMN user_id BINARY(16) NOT NULL;
