bind 0.0.0.0
port 6379
tcp-backlog 511

daemonize no
supervised no
pidfile /var/run/redis.pid

loglevel notice
logfile ""

maxmemory 256mb
maxmemory-policy allkeys-lru

save 900 1
save 300 10
save 60 10000

rdbcompression yes
dir /data
dbfilename dump.rdb

requirepass 1234
protected-mode yes

appendonly no
appendfilename "appendonly.aof"
appendfsync everysec

latency-monitor-threshold 0
tcp-keepalive 300
